name: Atualizar Branches

on:
  pull_request:
    types:
      - closed

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update branches
        run: |
            git remote update
            git fetch --all
            git push --all origin
